### PR TITLE
migration to postgresql

### PR DESCRIPTION
**Pull request by thequbit**

### CODE REVIEW

**Comment by thequbit** [comment]
The following commands showed that this worked as expected:

    $ git clone https://github.com/thequbit/yellr-server
    $ cd yellr-server
    $ cd yellr-serv
    $ python setup.py develop
    $ initialize_yellr-serv_db development.ini
    $ sqlite3 yellr-serv.sqlite < ./zipcodes/insert_zips_sqlite.sql
    $ pserve development.ini

In a new terminal:

    $ cd yellr-server
    $ pip install requests
    $ python tests.py

To make moderator interface:

    $ source ~/.nvm/nvm.sh
    $ nvm use v0.10.24
    $ make



As far as I can tell all features are working as expected, the android app also works as expected with the code migration.

**Comment by thequbit** [comment]
@Nolski if you could pull this down that would be awesome, if not I'll merge tomorrow.

**Comment by Nolski** [comment]
I'll test this out tomorrow when I get to school and let you know of any issues that I run into.

**Comment by thequbit** [comment]
Unfortunately we're rapidly approaching the point where sqlite will no longer work for testing,  since we'll be using the geo calculation functions of postgresql.

**Comment by Nolski** [comment]
Can you explain why exactly we need to make this big switch to postgres?

**Comment by thequbit** [comment]
Great question.

PostgreSQL has quite a bit more support for geometry and geography calculations.  Primary, polygon interaction.  Since android phones can exist in a state where a location is not shared with apps running on the device (by turning off location services), we default to a 'home zipcode'.

In the example of 14623, the 'center' of the zipcode is proximately 43.1687, -77.6158.  If a geo-fence was drawn around RIT, then someone who set their home zipcode as 14623 would not get any of the assignments for that geo-fence.

What we want is the polygon that is the entire 14623 zipcode, and look to see if there are any assignment geo-fences that are inside, intersect, or touch (single point) that polygon.

This can be done with MySQL 5.6 and later.  There is, however, no native support for the geometry (point, polygon, line, etc) within SQLAlchemy.  There is a great extension to SQLAlchemy that allows for support for these functions called GeoAlchemy.

GeoAlchemy is not supported in python 2.7 (wat.).

GeoAlchemy2 is supported in 2.7 and 3.x, nice!  GeoAlchemy2 is PostgreSQL only ...

The problem comes that the ORM that we picked (SQLAlchemy) does not have native support for the geometric functions we need to use to perform the queries necessary to maximize the usefulness of the geo-fencing technology we've picked.  There is an extension to SQLAchemy that allows us to take advantage of the functions we need, however it only supports PostgreSQL, not MySQL.

Does that clear things up?  I did, what I felt was, a decent amount of research to see if we could stick with MySQL, however after looking I did not see anyway we could stay with it and not migrate to using stored procedures, in-line SQL, or moving to PostgreSQL.  I picked migrating to PostgreSQL since I felt it was the most pythonic, and the cleanest solution.

**Comment by Nolski** [comment]
Perhaps I missed something but I still don't quite understand the _feature_ that requires this. If we are getting the users location, we shouldn't need to make a massive backend migration to Postgres to do that.

**Comment by thequbit** [comment]
If the user has location services turn off,  that is that they are not
sharing a location, the app becomes useless since we've based everything
around location.

If I opened the app,  and did not want to share my location it would
default to the center of my zipcode.   If a geo fence is drawn within my
zipcode, but not encompassing the center point,  I would not see it.

The proposed solution is to check if any assignments geo fence is inside or
touching the entire zipcode polygon,  and then return the assignments that
meet the criteria.

Using just sqlalchemy we can test for a point in a rectangle.   Using
geoalchemy we can test for polygon intersection.

I was able to successfully implement the desired operation using mysql 5.6,
however it requires the use of stored procedures.  I personally don't care
for stored procedures, as they can be difficult to version control.
Additionally it would make using sqlite impossible (although with
geoalchemy that is also true).

**Comment by Nolski** [comment]
This doesn't seem to be core to Yellr. There could be an argument made saying if you want to use geo-location features without giving your location to the server, then this app simply isn't right for you. Requiring to use GPS data for an app that is __centered around geographic data__ is not an unreasonable thing for an app to ask. Even Google Maps does that. 

On top of that this seems like a very small edge case and I think that migrating not only our entire database backend but also the ORM that uses it two weeks before Libre Planet is not a wise decision. I'm okay with keeping this as an open issue but I have to really push that I think that there is a time and place for this sort of change and now does not seem to be that time.

**Comment by thequbit** [comment]
First, I agree with the concerns due to the proximity to LibrePlanet.

Second, if you do have location services turned on, MySQLworks as expected (we query for the assignments and stories that have your lat/lng inside of their geofense).  If you have location services turned off, we get null, null back for the location, even if the permissions are set appropriately (sharing course and fine location).

What I think I would like to propose (at least until after LibrePlanet when we can continue the conversation), is that I remove the zipcode entry screen of the Android app, and we simply just block on location services not being enabled ( a dialog box shows up and the only option is to take you to location settings):



This allows us to maintain the same mysql-based back-end code.  We can discuss some options for 'obfuscating' the location by adding random amounts of distance to the result from the phone if needed.

@Nolski does this work for you?

Note: the changes in this PR do still work with sqlite, mysql, and now postgresql.  The changes do not force us to use postgresql (more importantly, this PR does not prevent us from continuing to use mysql).

**Comment by Nolski** [comment]
I really like this idea! Google Maps does this too and it seems to make a lot of sense and it allows us to pursue other options later on for geo-location stuff. I haven't pulled the code down yet but I'll see if I can do that between classes later today and if not, tomorrow.

**Comment by thequbit** [comment]
@Nolski glad we were able to come to a middle ground :D. collaboration for the win.  Let me know how you do with the code.  More code clean up to come (technical debt reduction ... buzzword buzzword buzzword).

**Comment by thequbit** [comment]
I discovered an issue that does not work with sqlite/mysql.  I am closing this PR, and resubmitting.

**Pull request closed without merging**
