### PR TITLE
change name of variable and formatting

### PR DESCRIPTION
**Pull request by thequbit**

### CODE REVIEW

**Comment by Nolski** [comment]
Er... Why is this change necessary? `post.text` doesn't exist and the posts themselves are working fine

**Comment by thequbit** [comment]
Let's do a quick Google hangout when you get a chance so we  can resolve this,  since it is working different on our two machines

**Comment by thequbit** [comment]
@Nolski 

Within app/templates/posts.html, I see have this code:

    <div class="posts">
    <div masonry load-images="false" masonry-options="{isFitWidth: true, gutter: 10, position: 'relative'}">
        <div ng-show="!posts.length === 0">
            <h4>No posts yet.</h4>
        </div>
        <div ng-show="posts.length" class="post-column masonry-brick"
            ng-repeat="post in posts | filter:search | postType:selectedType">
            <div class="inner-post">
                <div ng-if="post.imageUrl" ng-style="post.imageUrl" ng-class="post.text ? 'post-image' : 'full-image'"></div>
                <div ng-if="!post.imageUrl" class="post-image post-image-blank">
                    <h2>Yellr</h2>
                </div>
                <div class="post-body">
                    <h4 class="post-title" ng-if="post.title">{{post.title}}</h4>
                    <p class="post-text">{{post.text}}</p>
                    <p class="post-assignment-name" ng-if="post.assignment_name">Assignment: {{post.assignment_name}}</p>
                    <p class="post-assignment-name" ng-if="!post.assignment_name">Free Post</p>
                    <p class="post-time"><i class="fa fa-clock-o"></i> {{post.time}}</p>
                    <button class="delete-post"><i class="fa fa-trash"></i></button>
                    <button class="add-post" dropdown-toggle="#drop-{{post.post_id}}"><i class="fa fa-plus"></i></button>
                    <ul id="drop-{{post.post_id}}" class="f-dropdown add-post-dropdown">
                        <li ng-repeat="collection in collections" ng-click="addPostToCollection(post, collection)">{{collection.name}}</li>
                    </ul>
                    <a class="view-post" href="#/view/{{post.post_id}}">VIEW POST</a>
                </div>
            </div>
        </div>
    </div>
    </div>

Specifically, line 9:

    <div ng-if="post.imageUrl" ng-style="post.imageUrl" ng-class="post.text ? 'post-image' : 'full-image'"></div>

and line 15:

    <p class="post-text">{{post.text}}</p>

reference post.text.

Within app/common/formatPostService.js, I have this code:

    'use strict';

    var moment = moment || {};

    angular
        .module('Yellr')
        .factory('formatPosts', function () {
            var _getFirstText = function (post) {
                var i, mediaObject;
                for (i = 0; i < post.media_objects.length; i++) {
                    mediaObject = post.media_objects[i];

                    if (mediaObject.media_type_name == 'text') {
                        post.contentTypes.push('text');
                        return mediaObject.media_text;
                    } else if (mediaObject.media_type_name == 'image') {
                        if ( mediaObject.caption !== '' ) {
                            return mediaObject.caption;
                        }
                    }
                }

                return null;
            },
            _getFirstImage = function (post) {
                var i, mediaObject;
                for (i = 0; i < post.media_objects.length; i++) {
                    mediaObject = post.media_objects[i];

                    if (mediaObject.media_type_name == 'image') {
                        post.contentTypes.push('image');
                        return {
                            'background-image': 'url(/media/' +
                                mediaObject.preview_file_name + ')'
                        };
                    }
                }
                return null;
            },

            formatPosts = function (posts) {
                for (var postId in posts) {
                    posts[postId].contentTypes = [];

                    posts[postId].time = moment(
                            posts[postId].post_datetime,
                            'YYYY-MM-DD HH:mm:ss')
                        .fromNow();
                    posts[postId].text = _getFirstText(
                                                    posts[postId]);
                    posts[postId].imageUrl = _getFirstImage(
                                                    posts[postId]);
                }

                return posts;
            };

            return formatPosts;
        });

Specifically, on line 49:

    posts[postId].text = _getFirstText(
                                                posts[postId]);

there is the assignment of post.text.  The _getFirstText() function, returns the text to be assigned.  In the event that the mediaObject.media_type_text is 'text', then it returns media_text.  In the event that mediaObject.media_type_text is 'image' it returns 'caption'.  On lines 13 - 20:

    if (mediaObject.media_type_name == 'text') {
        post.contentTypes.push('text');
        return mediaObject.media_text;
    } else if (mediaObject.media_type_name == 'image') {
        if ( mediaObject.caption !== '' ) {
            return mediaObject.caption;
        }
    }

I am more than willing to open a dialog about how we change the response of this end-point, I agree that it isn't done the best way.

Let me know if this is what you see on your end.

**Comment by Nolski** [comment]
So first things first. It doesn't seem like you are up to date with hhroc. As you can see here: https://github.com/hhroc/yellr-server/blob/master/app/templates/posts.html#L15 line 15 of posts.html is not what you are showing from above. So I'd make sure that your head is at the same place as `hhroc/master`.

Secondly, it looks like when you rewrote & merged the controller the nomenclature for the post's description (previously `post.description` was changed to `post.text` so I'll make that change and grep for `.text` anywhere and make sure it's `.description`.

**Pull request closed without merging**
