### PR TITLE
Fixed numerous issues with collection dropdown not working

### PR DESCRIPTION
**Pull request by Nolski**
On the view collection page, the add to collection button just no longer shows up.

On the assignment page it now works properly.

### CODE REVIEW

**Comment by thequbit** [comment]
This is what I'm seeing:



Doesn't appear to be fixed.  Note the URL, I am on a collections page.  Additionally, the Collections nav link is highlighted so i believe I have the correct code (not cached by browser).  This was tested in Chrome.

**Comment by thequbit** [comment]
Lovely ... this works as expected in Firefox 35.0.1 ... does not work in Chrome 40.0.2214.115 m.

**Comment by Nolski** [comment]
Are you sure? I made and cleaned. The code is there and it built fine and here is what I see. Tested in both firefox and chrome.

screen shot 2015-03-02 at 3 17 13 pm

**Comment by thequbit** [comment]
When done in incognito mode ... not sure why chrome wasn't letting go of the cache, did all the things i could.

**Pull request merged**
