### PR TITLE
fixed posting images, vote colors, and icon fonts

### PR DESCRIPTION
**Pull request by thequbit**

### CODE REVIEW

**Comment by Nolski** [comment]
When you make a post that has both an image or text, it sends *just* the image to the server. If this is how we want to make posts then fine but it should be more of a modal selection between the two.

**Comment by Nolski** [comment]
Oh also it looks like the time of the post is messed up. Even though I made the post a few minutes ago, the post says that it was made 20 hours ago.

screenshot 2015-04-22 15 03 32

**Comment by thequbit** [comment]
Fixed image/text not posting together, and fixed datetime display.

**Comment by thequbit** [comment]
@Nolski ran out of time for review :(  ... submit bugs if ya find em.

**Pull request merged**
