### PR TITLE
closing mad tickets.

### PR DESCRIPTION
**Pull request by thequbit**
Ass a quick UI tweak to allow for posts to be un-approved.

### CODE REVIEW

**Comment by thequbit** [comment]
Docs:
https://github.com/hhroc/yellr-server/wiki/admin-get_assignments.json

**Comment by thequbit** [comment]
This is ... probably bigger than it should be, but each ticket was pretty small.

Closes #183, #190, #193, #194, #196, #199, #221, and #222

**Comment by thequbit** [comment]
@Nolski review, and close those tickets when you're happy.

**Comment by thequbit** [comment]
Not entirely sure why this failed, looking into it now.

**Comment by thequbit** [comment]
forgot to add new settings sass files, pushed and will see if Travis is happy.

**Comment by thequbit** [comment]
Also closes #26

**Comment by thequbit** [comment]
uh ... @Nolski did this fail because Travis lost network connectivity? Or am I misreading that log?

**Comment by thequbit** [comment]
Adjusted fix for #26, hopefully that makes travis happy again ...

**Comment by thequbit** [comment]
Nice.  @Nolski merge at your convenience.

**Comment by Nolski** [comment]
LGTM :facepunch:

**Pull request merged**
